---
- name: Install HDSearch
  hosts: 
  - midtier
  - bucket
  tasks:    
  - name: Install HDSearch if not exists
    unarchive: 
      src: ~/HDSearch.tgz 
      dest: ~/

  - name: Set Up Docker
    become: yes
      tasks:
      - name: Set Up Docker Curl
        command: ~/HDSearch/scripts/set-up-docker.sh
        async: 10000 
        poll: 0
  
  - name: Change Storage Folder
    become: yes
      tasks:
    - name: Make Space to Commit Image
      command: ~/HDSearch/scripts/change-storage-location-docker.sh
      async: 10000 
      poll: 0

- name: Execute HDSearch Container 
  become: yes
  hosts:
  - midtier
  #- bucket
  #- client
  tags: compose_up_hdsearch
  tasks:
    - name: Change to docker group 
      command: sudo newgrp docker
    - name: Compose Up HDSearch 
      command: cd ~/HDSearch/microsuite; sudo docker compose up