---
- name: Install HDSearch
  hosts: 
  - midtier
  - bucket
  tasks:    
  - name: Install HDSearch if not exists
    unarchive: 
      src: ~/HDSearch.tgz 
      dest: ~/
- name: Execute HDSearch Container 
  become: yes
  hosts:
  - midtier
  #- bucket
  #- client
  tags: compose_up_hdsearch
  tasks:
    - name: Change to docker group 
      command: sudo newgrp docker
    - name: Compose Up HDSearch 
      command: docker compose up